export enum SubscriberEnum {
    TABLE_GET_TEXT_FROM_FORMULA = "TABLE_GET_TEXT_FROM_FORMULA",
    GET_TEXT_CURRENT_SECTION = "GET_TEXT_CURRENT_SECTION",
    CLICK_TOOLBAR = "CLICK_TOOLBAR",
    GET_NAME = "GET_NAME"
}